---
title: "Untitled"
author: "Justin Lewinski"
date: "2023-05-16"
output: html_document
---
```{r}
library(readr)
library(tidyverse)
library(ggplot2)
library(caret)
library(plotROC)
library(ggcorrplot)
library(ISLR)
library(yardstick)
library(tidyverse)
library(rsample)
library(glmnet)
library(glmnetUtils)
library(forcats)
library(randomForestExplainer)
library(ggplot2)
library(randomForest)

```

# 2

```{r}
data <- read_csv('datasets/booking-1.csv')
data %>% summary()
data_clean <- 
  data %>% 
  mutate(reviewscore2 = hotel_review_score**2,
         hotel_stars2 = hotel_stars**2,
         price2 = price_usd**2,
         booking_window_2 = booking_window**2) 

```
```{r}
ggplot(data_clean, aes(x = price_usd, y = hotel_location_score)) + geom_point(alpha = 0.2) + geom_smooth(method = lm) + theme_minimal()
```

```{r}
ggplot(data_clean, aes(x = length_of_stay, y = booking_window)) + geom_point(alpha = 0.2) + geom_smooth(method = lm) + theme_minimal()
```

# 3

```{r}
set.seed(2370404)
initial_split_hotel <- initial_split(data_clean, prop = .75)
hotel_train <- training(initial_split_hotel)
hotel_test <- testing(initial_split_hotel)

```


```{r}
hotel_train %>% glimpse

```
```{r}
logit <- glm(booking ~ hotel_stars + hotel_review_score + hotel_chain + 
                       hotel_location_score + hotel_historical_price + search_ranking
                       + price_usd + promotion + length_of_stay + booking_window + 
                         adults_count + children_count + room_count + saturday_night
                       + comp_rate + comp_inv, data = hotel_train, family = binomial)
logit %>% summary()

```
```{r}
exp(logit$coefficients)

```

```{r}
scores_train <- predict(logit, typ = "response")
scores_test <- predict(logit, type = "response", newdata = hotel_test)

```

```{r}
predicted_train<- ifelse(scores_train>0.5,"1","0")
head(predicted_train)

predicted_test <-  ifelse(scores_test>0.5,"1","0")
head(predicted_test)
```
```{r}
results_train <- data.frame(
  true = factor(hotel_train$booking),
  predicted = factor(predicted_train),
  score = scores_train)
sum(results_train$predicted == 1)
sum(results_train$predicted == 0)

results_test <- data.frame(
  true = factor(hotel_test$booking),
  predicted = factor(predicted_test),
  score = scores_test)
results_test %>% glimpse()

```
```{r}
cm_trainlogit <- conf_mat(results_train,
               truth = true,
               estimate = predicted)

cm_testlogit <- conf_mat(results_test,
               truth = true,
               estimate = predicted)

print(cm_trainlogit)
print(cm_testlogit)


TN_trainlogit = 1022
TP_trainlogit = 374
FN_trainlogit = 348
FP_trainlogit = 230



TN_testlogit = 353
TP_testlogit = 134
FN_testlogit = 98
FP_testlogit = 73
```

```{r}

print('train_scores')

acc_trainlogit = (TN_trainlogit +TP_trainlogit ) / (TN_trainlogit + TP_trainlogit + FN_trainlogit + FP_trainlogit)
print(acc_trainlogit)


sen_trainlogit = TP_trainlogit/(TP_trainlogit +FN_trainlogit)
print(sen_trainlogit)



spe_trainlogit = TN_trainlogit/(TN_trainlogit + FP_trainlogit)

print(spe_trainlogit)


print('test scores')
acc_testlogit = (TN_testlogit +TP_testlogit ) / (TN_testlogit + TP_testlogit + FN_testlogit + FP_testlogit)
print(acc_testlogit)


sen_testlogit = TP_testlogit/(TP_testlogit +FN_testlogit)
print(sen_testlogit)



spe_testlogit = TN_testlogit/(TN_testlogit + FP_testlogit)

print(spe_testlogit)

```



```{r}
bag_hotel <- randomForest(booking ~ hotel_stars + hotel_review_score + hotel_chain + 
                       hotel_location_score + hotel_historical_price + search_ranking
                       + price_usd + promotion + length_of_stay + booking_window + 
                         adults_count + children_count + room_count + saturday_night
                       + comp_rate + comp_inv, data = hotel_train)
print(bag_hotel)
plot(bag_hotel)
```



```{r}
scores_trainbag <- predict(bag_hotel, typ = "response")
scores_testbag <- predict(bag_hotel, type = "response", newdata = hotel_test)

predicted_trainbag<- ifelse(scores_trainbag>0.5,"1","0")
head(predicted_trainbag)

predicted_testbag <-  ifelse(scores_testbag>0.5,"1","0")
head(predicted_testbag)
```
```{r}
results_trainbag <- data.frame(
  true = factor(hotel_train$booking),
  predicted = factor(predicted_trainbag),
  score = scores_trainbag)
sum(results_trainbag$predicted == 1)
sum(results_trainbag$predicted == 0)

results_testbag <- data.frame(
  true = factor(hotel_test$booking),
  predicted = factor(predicted_testbag),
  score = scores_testbag)
results_testbag %>% glimpse()
```

```{r}
cm_trainbag <- conf_mat(results_trainbag,
               truth = true,
               estimate = predicted)

cm_testbag <- conf_mat(results_testbag,
               truth = true,
               estimate = predicted)
print(cm_trainbag)
print(cm_testbag)

TN_trainbag = 1108
TP_trainbag = 443
FN_trainbag = 279
FP_trainbag = 144

TN_testbag = 379
TP_testbag = 151
FN_testbag = 81
FP_testbag = 47
```
```{r}
print('train scores forest')

acc_trainbag = (TN_trainbag +TP_trainbag ) / (TN_trainbag + TP_trainbag + FN_trainbag + FP_trainbag)
print(acc_trainbag)


sen_trainbag = TP_trainbag/(TP_trainbag +FN_trainbag)
print(sen_trainbag)



spe_trainbag = TN_trainbag/(TN_trainbag + FP_trainbag)

print(spe_trainbag)


print('test scores forest')
acc_testbag = (TN_testbag +TP_testbag ) / (TN_testbag + TP_testbag + FN_testbag + FP_testbag)
print(acc_testbag)


sen_testbag = TP_testbag/(TP_testbag +FN_testbag)
print(sen_testbag)



spe_testbag = TN_testbag/(TN_testbag + FP_testbag)

print(spe_testbag)


```

```{r}
print('Logit Model Test')
print(cm_testlogit)

print('Bagging Model Test')
print(cm_testbag)
```


```{r}
print('TP % Increase From logit to bag = ') 
print(1 - (TP_testlogit/TP_testbag))

print('TN % Increase From logit to bag = ') 
print(1 - (TN_testlogit/TN_testbag))

print('FP % decrease From logit to bag = ') 
print(1 - (FP_testbag/FP_testlogit))

print('FN % decrease From logit to bag = ') 
print(1 - (FN_testbag/FN_testlogit))
```

# 5
```{r}
bag_hotel2 <- randomForest(booking ~ hotel_stars + hotel_review_score + hotel_chain + 
                       hotel_location_score + hotel_historical_price + search_ranking
                       + price_usd + promotion + length_of_stay + booking_window + 
                         adults_count + children_count + room_count + saturday_night
                       + comp_rate + comp_inv + reviewscore2 + hotel_stars2 + price2 + booking_window_2, data = hotel_train)
print(bag_hotel2)
plot(bag_hotel2)
```

```{r}
scores_trainbag2 <- predict(bag_hotel2, typ = "response")
scores_testbag2 <- predict(bag_hotel2, type = "response", newdata = hotel_test)

predicted_trainbag2<- ifelse(scores_trainbag>0.5,"1","0")
head(predicted_trainbag2)

predicted_testbag2 <-  ifelse(scores_testbag>0.5,"1","0")
head(predicted_testbag2)
```

```{r}
results_trainbag2 <- data.frame(
  true = factor(hotel_train$booking),
  predicted = factor(predicted_trainbag2),
  score = scores_trainbag2)
results_testbag2 <- data.frame(
  true = factor(hotel_test$booking),
  predicted = factor(predicted_testbag2),
  score = scores_testbag2)

results_testbag %>% glimpse()
sum(results_trainbag2$predicted == 1)
sum(results_trainbag2$predicted == 0)


cm_trainbag2 <- conf_mat(results_trainbag2,
               truth = true,
               estimate = predicted)

cm_testbag2 <- conf_mat(results_testbag2,
               truth = true,
               estimate = predicted)
print(cm_trainbag2)
print(cm_testbag2)

TN_trainbag2 = 1116
TP_trainbag2 = 445
FN_trainbag2 = 277
FP_trainbag2 = 136

TN_testbag2 = 379
TP_testbag2 = 160
FN_testbag2 = 72
FP_testbag2 = 47




```

```{r}
print('test scores forest improved model')
acc_testbag2 = (TN_testbag2 +TP_testbag2 ) / (TN_testbag2 + TP_testbag2 + FN_testbag2 + FP_testbag2)
print(acc_testbag2)


sen_testbag2 = TP_testbag2/(TP_testbag2 +FN_testbag)
print(sen_testbag2)



spe_testbag2 = TN_testbag2/(TN_testbag2 + FP_testbag2)

print(spe_testbag2)



```



# 6
```{r}
library(factoextra)

searchers <- data %>% 
  group_by(srch_id) %>% 
  summarize(across(where(is.numeric), mean)) 




```














